// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CanWePatch() {
  return window['go']['main']['App']['CanWePatch']();
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function DownloadAndInstallPatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadAndInstallPatch'](arg1, arg2, arg3, arg4);
}

export function FetchGameVersion() {
  return window['go']['main']['App']['FetchGameVersion']();
}

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IniToObject() {
  return window['go']['main']['App']['IniToObject']();
}

export function InstallAllPatches(arg1, arg2) {
  return window['go']['main']['App']['InstallAllPatches'](arg1, arg2);
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function NostalgiaIniPath() {
  return window['go']['main']['App']['NostalgiaIniPath']();
}

export function NostalgiaSettingsJsonPath() {
  return window['go']['main']['App']['NostalgiaSettingsJsonPath']();
}

export function ObjectToIniFile(arg1) {
  return window['go']['main']['App']['ObjectToIniFile'](arg1);
}

export function OptionIniPath() {
  return window['go']['main']['App']['OptionIniPath']();
}

export function ReadNostalgiaSettingsJson() {
  return window['go']['main']['App']['ReadNostalgiaSettingsJson']();
}

export function RemovePatchZip(arg1) {
  return window['go']['main']['App']['RemovePatchZip'](arg1);
}

export function Unzip(arg1) {
  return window['go']['main']['App']['Unzip'](arg1);
}

export function UpdateCheckUI() {
  return window['go']['main']['App']['UpdateCheckUI']();
}

export function UpdateGameVersion(arg1) {
  return window['go']['main']['App']['UpdateGameVersion'](arg1);
}
